### ISSUE TITLE
This site can't be reached after i hit the download button

### ISSUE THREAD

**Issue by vpoptani** [ThinkingStudio/SonarExport#2]
Hello @greenlaw110 

I tried out this application and used it to download the report for my sonarqube project, i downloaded the project as a zip and uzipped it. Then i did a mvn clean compile exec:exec as advised in the readme.md, the application at localhost:5460 was up and as soon as i click on the download button i get a prompt saying the site cannot be reached. 

```
Logs --> 06:56:07.129 [main] INFO  a.a.App - App[Sonar Issue Exporter] loaded in 4581ms
06:56:07.153 [jobs-thread-2] INFO  a.Act - start compiling API book
06:56:07.181 [main] INFO  o.xnio - XNIO version 3.3.8.Final
06:56:07.223 [main] INFO  o.x.nio - XNIO NIO Implementation Version 3.3.8.Final
06:56:07.453 [main] INFO  a.Act - network client hooked on port: 5460
06:56:07.462 [main] INFO  a.Act - CLI server started on port: 5461
06:56:07.473 [main] INFO  a.Act - it takes 13154ms to start the app

06:57:10.584 [XNIO-1 task-4] ERROR a.h.b.c.RequestHandlerProxy - Error handling request: [GET] /report/xlsx
com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.39
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:451)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:271)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:640)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:364)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:268)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:487)
        at com.pixolut.sonar.Report.report(Report.java:44)
        at com.pixolut.sonar.ReportMethodAccess.invoke(Unknown Source)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:650)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:332)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:53)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:494)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
        at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
        at act.route.Router$ContextualHandler.handle(Router.java:1341)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
06:57:11.030 [XNIO-1 task-5] ERROR a.h.b.c.RequestHandlerProxy - Error handling request: [GET] /report/xlsx
com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.39
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:451)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:271)
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:267)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:640)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:364)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:268)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:487)
        at com.pixolut.sonar.Report.report(Report.java:44)
        at com.pixolut.sonar.ReportMethodAccess.invoke(Unknown Source)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:650)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:332)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:53)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:494)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:203)
        at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
        at act.route.Router$ContextualHandler.handle(Router.java:1341)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
06:57:16.277 [XNIO-1 task-6] ERROR a.h.b.c.RequestHandlerProxy - Error handling request: [GET] /report/xlsx
com.alibaba.fastjson.JSONException: syntax error, expect {, actual error, pos 0, fastjson-version 1.2.39
        at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:451)
```

**Comment by chortels** [comment]
Hi @greenlaw110 , 

Do you have any estimation about when will this bug be solved? We're looking forward to using this functionality in our SonarQube application. 

Regards!

**Comment by greenlaw110** [comment]
@vpoptani and @chortels 

I will work on this tomorrow and get it sorted out

**Comment by chortels** [comment]
Hi @greenlaw110 , any progress on this?

Regards!

**Comment by greenlaw110** [comment]
@chortels doing that now ...

**Comment by greenlaw110** [comment]
@chortels and @vpoptani Just pushed the change, can you please try again?
